backend/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile_detail'),
    path('profile/<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile_update'),
    # Signup
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup_done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('signup_complete/<token>/', views.SignupCompleteView.as_view(), name='signup_complete'),
    # Login and Logout
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Password Change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('welcome.urls')),
    path('accounts/', include('accounts.urls')),
    path('speaks/', include('speaks.urls')),
    path('scraping/', include('scraping.urls')),
    path('video/', include('video.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

backend/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

backend/scraping/urls.py
from django.urls import path

from . import views

app_name = 'scraping'
urlpatterns = [
    path('', views.ScrapingHomeView.as_view(), name='home'),
    path('create', views.ScrapingCreateView.as_view(), name='create_scraping'),
]

backend/speaks/urls.py
from django.urls import path
from . import views

app_name = 'speaks'
urlpatterns = [
    path('', views.SpeakListView.as_view(), name='speak_list'),
    path('new/', views.SpeakCreateView.as_view(), name='speak_create'),
    path('<pk>/', views.SpeakReadView.as_view(), name='speak_read'),
    path('<pk>/update', views.SpeakUpdateView.as_view(), name='speak_update'),
    path('<pk>/delete', views.SpeakDeleteView.as_view(), name='speak_delete'),
]

backend/video/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

backend/templates/parts/basic_form.html
{% load widget_tweaks %}
<form method="post">
  {% csrf_token %}
  
  {% for field in form %}
    <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
        {% if field.errors %}

        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
            <div class="invalid-feedback">
            {{ error }}
            </div>
        {% endfor %}

        {% else %}
        {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
        <small class="form-text text-muted">
        {{ field.help_text }}
        </small>
    {% endif %}
    </div>
  {% endfor %}
  <input type="submit" value="{{ text | default:"Submit" }}" class="mt-3 btn btn-primary" />
</form>

backend/templates/parts/global_navi.html
{% load menu_link_tags %}

<div class="container">
    <div class="row">
        <ul class="d-flex list-unstyled">
            <li class="px-2">
                {% url 'accounts:home' as url_accounts_home %}
                {% menu_link url_accounts_home request.get_full_path "Home" %}
            </li>
            <li class="px-2">
                {% url 'accounts:profile_detail' request.user.profile.id as url_accounts_profile_detail %}
                {% menu_link url_accounts_profile_detail request.get_full_path "Profile" %}
            </li>
            <li class="px-2">
                {% url 'scraping:home' as url_scraping_home %}
                {% menu_link url_scraping_home request.get_full_path "Scraping" %}
            </li>
            <li class="px-2">
                {% url 'speaks:speak_create' as url_speaks_speak_create %}
                {% menu_link url_speaks_speak_create request.get_full_path "Speak" %}
            </li>
            <li class="px-2">
                {% url 'accounts:settings' as url_accounts_settings %}
                {% menu_link url_accounts_settings request.get_full_path "Settings" %}
            </li>
        </ul>
    </div>
</div>

backend/templates/parts/pagination.html
<div class="col-12">
    <ul class="pagination">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
    
        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
    
        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

backend/templates/parts/speak_list.html
{% for speak in speaks %}
    <div class="col-12 d-flex px-4">
        <div class="icon-wrapper px-2 flex-shrink-1">
            <a href="{% url 'accounts:profile_detail' speak.user.profile.id %}">
                <img src='{{ speak.user.profile.icon_image.url }}' class="rounded-circle" style="height: 40px; width: 40px; object-fit: cover;">
            </a>
        </div>
        <div class="content-wrapper w-100 px-2">
            <div class="content-header d-flex justify-content-between align-items-center w-100">
                <a href="{% url 'accounts:profile_detail' speak.user.profile.id %}" class="text-body fw-bold text-decoration-none">{{ speak.user }}</a>
                <div class="dropdown">
                    <div id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-ellipsis-h"></i>
                    </div>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'speaks:speak_read' speak.id %}">Read</a></li>
                        {% if request.user == speak.user %}
                        <li><a class="dropdown-item" href="{% url 'speaks:speak_update' speak.id %}">Update</a></li>
                        <li><a class="dropdown-item" href="{% url 'speaks:speak_delete' speak.id %}">Delete</a></li>
                        {% endif %}
                    </ul> 
                </div>
            </div>
            <p>{{ speak.content|linebreaksbr }}</p>
            <div class="content-footer">
                <ul class="d-flex list-unstyled justify-content-between align-items-center w-100 m-0">
                    <li><i class="far fa-comments"></i></li>
                    <li><i class="fas fa-retweet"></i></li>
                    <li><i class="far fa-heart"></i></li>
                    <li><i class="fas fa-share-alt"></i></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-12">
        <hr>
    </div>
{% endfor %}