backend/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile_detail'),
    path('profile/<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile_update'),
    # Signup
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup_done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('signup_complete/<token>/', views.SignupCompleteView.as_view(), name='signup_complete'),
    # Login and Logout
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Password Change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('welcome.urls')),
    path('accounts/', include('accounts.urls')),
    path('speaks/', include('speaks.urls')),
    path('scraping/', include('scraping.urls')),
    path('video/', include('video.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

backend/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

backend/speaks/urls.py
from django.urls import path
from . import views

app_name = 'speaks'
urlpatterns = [
    path('', views.SpeakListView.as_view(), name='speak_list'),
    path('new/', views.SpeakCreateView.as_view(), name='speak_create'),
    path('<pk>/', views.SpeakReadView.as_view(), name='speak_read'),
    path('<pk>/update', views.SpeakUpdateView.as_view(), name='speak_update'),
    path('<pk>/delete', views.SpeakDeleteView.as_view(), name='speak_delete'),
]

backend/video/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

backend/speaks/models.py
from django.db import models

# Create your models here.
class Speak(models.Model):
    content = models.TextField(
        max_length=140
    )
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return self.content
    
    def excerpted_content(self):
        return self.content[:20]

backend/speaks/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DeleteView, DetailView, ListView, UpdateView

from .models import Speak

class SpeakListView(ListView):
    model = Speak
    context_object_name = 'speaks'
    template_name = 'speaks/speak_list.html'


class SpeakCreateView(LoginRequiredMixin, CreateView):
    model = Speak
    fields = ['content']
    template_name = 'speaks/speak_create.html'
    success_url = reverse_lazy('accounts:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SpeakReadView(DetailView):
    model = Speak
    template_name = 'speaks/speak_read.html'
    context_object_name = 'speak'


class SpeakUpdateView(LoginRequiredMixin, UpdateView):
    model = Speak
    fields = ['content']
    template_name = 'speaks/speak_update.html'
    success_url = reverse_lazy('accounts:home')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class SpeakDeleteView(LoginRequiredMixin, DeleteView):
    model = Speak
    template_name = 'speaks/speak_delete.html'
    success_url = reverse_lazy('accounts:home')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

backend/speaks/templates/speaks/speak_create.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Speak{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container d-flex justify-content-center">
    <div class="card w-100">
        <div class="card-body">
            <h2 class="card-title">Speak</h2>
            <a href="{% url 'speaks:speak_list' %}">Speaks一覧</a>
            <form method="post">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field.errors %}

                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                        {{ error }}
                        </div>
                    {% endfor %}

                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">
                    {{ field.help_text }}
                    </small>
                {% endif %}
                </div>
                {% endfor %}

                <input type="submit" value="Submit" class="mt-3 btn btn-primary" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/speaks/templates/speaks/speak_delete.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Speak Delete{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container d-flex justify-content-center">
    <div class="card w-100">
        <div class="card-body">
            <h2 class="card-title">Delete Speak</h2>
            <form method="post">
                {% csrf_token %}
                
                <input type="submit" value="Delete" class="mt-3 btn btn-danger" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/speaks/templates/speaks/speak_list.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Speaks一覧{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container">
    <div class="row">
        {% include "parts/speak_list.html" with speaks=speaks %}
    </div>
    <div class="row">
        {% include "parts/pagination.html" %}
    </div>
</div>
{% endblock %}

backend/speaks/templates/speaks/speak_read.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Speak Detail{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container">
    <div class="row">
        <div class="col-12 d-flex px-4">
            <div class="icon-wrapper px-2 flex-shrink-1">
                <a href="{% url 'accounts:profile_detail' speak.user.profile.id %}">
                    <img src='{{ speak.user.profile.icon_image.url }}' class="rounded-circle" style="height: 40px; width: 40px; object-fit: cover;">
                </a>
            </div>
            <div class="content-wrapper w-100 px-2">
                <div class="content-header d-flex justify-content-between align-items-center w-100">
                    <a href="{% url 'accounts:profile_detail' speak.user.profile.id %}" class="text-body fw-bold text-decoration-none">{{ speak.user }} <span class="text-muted fw-lighter">{{ speak.user.uuid }}</span></a>
                    <div class="dropdown">
                        <div id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-ellipsis-h"></i>
                        </div>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            {% if request.user == speak.user %}
                            <li><a class="dropdown-item" href="{% url 'speaks:speak_update' speak.id %}">Update</a></li>
                            <li><a class="dropdown-item" href="{% url 'speaks:speak_delete' speak.id %}">Delete</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="content-text">
                    <p>{{ speak.content|linebreaksbr }}</p>
                </div>
                <div class="content-time ">
                    <hr class="my-1">
                    <time class="text-muted">{{ speak.updated_at|date:'H:i Y/m/d' }}</time>
                    <hr class="my-1">
                </div>
                <div class="content-footer">
                    <ul class="d-flex list-unstyled justify-content-between align-items-center w-100 m-0">
                        <li><i class="far fa-comments"></i></li>
                        <li><i class="fas fa-retweet"></i></li>
                        <li><i class="far fa-heart"></i></li>
                        <li><i class="fas fa-share-alt"></i></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>
</div>
{% endblock %}

backend/speaks/templates/speaks/speak_update.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Speak Update{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container d-flex justify-content-center">
    <div class="card w-100">
        <div class="card-body">
            <h2 class="card-title">Speak Update</h2>
            <form method="post">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field.errors %}

                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                        {{ error }}
                        </div>
                    {% endfor %}

                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">
                    {{ field.help_text }}
                    </small>
                {% endif %}
                </div>
                {% endfor %}

                <input type="submit" value="Submit" class="mt-3 btn btn-primary" />
            </form>
        </div>
    </div>
</div>
{% endblock %}