backend/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile_detail'),
    path('profile/<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile_update'),
    # Signup
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup_done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('signup_complete/<token>/', views.SignupCompleteView.as_view(), name='signup_complete'),
    # Login and Logout
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Password Change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('welcome.urls')),
    path('accounts/', include('accounts.urls')),
    path('speaks/', include('speaks.urls')),
    path('scraping/', include('scraping.urls')),
    path('video/', include('video.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

backend/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

backend/video/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
import uuid as uuid_lib
from django.utils import timezone
from django.core.mail import send_mail

class UserManager(BaseUserManager):
    use_in_migrations = True
  
    def _create_user(self, email, password, **extra_fields):
        """Create and save a user with the given username, email, and
        password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
  
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
  
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
  
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
  
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
  
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(
        default=uuid_lib.uuid4,
        primary_key=True, 
        editable=False
    )
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[UnicodeUsernameValidator()],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(
        _('email address'),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(
        _('date joined'), 
        default=timezone.now
    )

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE
    )
    text = models.TextField(
        max_length=140, 
        blank=True, 
        null=True, 
        default=''
    )
    icon_image = models.ImageField(
        default='profile/default_icon.jpg', upload_to='profile/icon_pics'
    )
    header_image = models.ImageField(
        default='profile/default_header.jpg', upload_to='profile/header_pics'
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

backend/speaks/models.py
from django.db import models

# Create your models here.
class Speak(models.Model):
    content = models.TextField(
        max_length=140
    )
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return self.content
    
    def excerpted_content(self):
        return self.content[:20]

backend/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        # When an user tries to recreate his/her new account with same email, delete the account, which is registerd with the email.
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

backend/accounts/views.py
from django.conf import settings
from django.shortcuts import redirect
from django.http import HttpResponseBadRequest
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.views.generic import ListView, DetailView, UpdateView, CreateView, TemplateView
from django.template.loader import render_to_string

from .forms import CustomUserCreationForm
from .models import Profile, User

from libraries.authentications import OnlyAnonymousUserMixin
from speaks.models import Speak

class SignupView(OnlyAnonymousUserMixin, CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(str(user.pk)),
            'user': user
        }
        subject = render_to_string('registration/signup_subject.txt', context)
        message = render_to_string('registration/signup_email.html', context)
        user.email_user(subject, message)
        return redirect('accounts:signup_done')


class SignupDoneView(OnlyAnonymousUserMixin, TemplateView):
    template_name = 'registration/signup_done.html'


class SignupCompleteView(OnlyAnonymousUserMixin, TemplateView):
    template_name = 'registration/signup_complete.html'
    max_age = settings.ACTIVATION_TIMEOUT_SECONDS

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.max_age)
        except SignatureExpired:
            return HttpResponseBadRequest()
        except BadSignature:
            return HttpResponseBadRequest()
        except Exception as e:
            return HttpResponseBadRequest()
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save(update_fields=['is_active'])
                    user = User.objects.get(pk=user_pk)
                    login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    return super().get(request, **kwargs)
        return HttpResponseBadRequest()


class HomeView(LoginRequiredMixin, ListView):
    template_name = "accounts/home.html"
    queryset = Speak.objects.order_by('-created_at')
    paginate_by = 4
    context_object_name = 'speaks'


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/settings.html'


class ProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'accounts/profile.html'
    context_object_name = 'profile'


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['text', 'icon_image', 'header_image']
    template_name = 'accounts/profile_update.html'
    context_object_name = 'profile'
    
    def get_success_url(self):
        return reverse(
            'accounts:profile_detail', 
            args=[self.kwargs['pk']]
            )

backend/accounts/templates/accounts/home.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Home{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container">
    <div class="row">
        {% include "parts/speak_list.html" with speaks=speaks %}
    </div>
    <div class="row">
        {% include "parts/pagination.html" %}
    </div>
</div>
{% endblock %}

backend/accounts/templates/accounts/profile.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}プロフィール{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <figure>
                <img src='{{ profile.header_image.url }}' class="figure-img img-fluid rounded" style="max-height: 80px; width: 100%;object-fit: cover;">
            </figure>
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex">
            <figure>
                <img src='{{ profile.icon_image.url }}' class="figure-img img-fluid rounded-circle" style="height: 120px; width: 120px; object-fit: cover;">
            </figure>
            <div class="profile ps-4 flex-grow-1">
                <div class="profile_header d-flex align-items-center justify-content-between">
                    <h2>{{ profile.user.username }}</h2>
                    <div>
                        {% if profile.user.uuid == request.user.uuid %}
                        <a href="{% url 'accounts:profile_update' user.profile.id %}" class="btn btn-sm btn-outline-info">編集</a>
                        {% endif %}
                    </div>
                </div>
                <div class="profile_content">
                    <p>{{ profile.text }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row">
        {% include "parts/speak_list.html" with speaks=profile.user.speak_set.all %}
    </div>
</div>
{% endblock %}

backend/accounts/templates/accounts/profile_update.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}プロフィール編集{{ block.super }}{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <div class="card w-100">
        <div class="card-body">
            <h2 class="card-title">Sign Up</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field.errors %}

                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                        {{ error }}
                        </div>
                    {% endfor %}

                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">
                    {{ field.help_text }}
                    </small>
                {% endif %}
                </div>
                {% endfor %}

                <input type="submit" value="Submit" class="mt-3 btn btn-primary" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/accounts/templates/accounts/settings.html
{% extends "common/base.html" %}
{% load widget_tweaks %}

{% block titele %}Home{{ block.super }}{% endblock %}

{% block content %}
{% include "parts/global_navi.html" %}

<div class="container">
    <div class="row">
        <ul class="list-unstyled">
            <li class="px-2">
                <a href="{% url 'accounts:password_change'%}">Password Change</a>
            </li>
        </ul>
    </div>
</div>
{% endblock %}